name: Semgrep

on:
  workflow_dispatch: {}

env:
  repo-path: ./server
  sca-stubs-path: ./sca-stubs
  sca-cache-key-root: stubs

jobs:
  generate-stubs:
    name: Generate Package Lock Stubs
    runs-on: ubuntu-24.04
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Stubs
        uses: ./.github/actions/new-sca-project-stubs
        with:
          repo-path: ${{ env.repo-path }}
          stub-project-path: ${{ env.sca-stubs-path }}

      - name: Save Project Stubs
        id: stubs-cache
        uses: actions/cache/save@v5
        with:
          enableCrossOsArchive: true
          path: ${{ env.sca-stubs-path }}/**
          key: ${{ env.sca-cache-key-root }}-${{ hashFiles('**/packages.config') }}

  semgrep:
    name: semgrep/ci
    needs: [generate-stubs]
    runs-on: ubuntu-24.04
    if: github.actor != 'dependabot[bot]'

    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add packages needed for actions/cache restore to work
        run: |
          apk update
          apk add --no-cache zstd tar

      - name: Restore Project Stubs
        id: stubs-cache
        uses: actions/cache/restore@v5
        with:
          fail-on-cache-miss: true
          enableCrossOsArchive: true
          path: ${{ env.sca-stubs-path }}/**
          key: ${{ env.sca-cache-key-root }}-${{ hashFiles('**/packages.config') }}

      - name: Run Semgrep
        run: semgrep ci --allow-local-builds --verbose
